### ISSUE TITLE
ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by kgg012392** [HaixinShi/fmov_pose#2]
I follow [these example scripts](https://github.com/HaixinShi/fmov_pose?tab=readme-ov-file#running) and face the following error:
```
Hello FMOV
Use global conf...
Load data: Begin
scale_mats_np 156
using partial annotation camera pose...
loading loftr interval flow... AP13
------start_idx 0
Load data: End
Using BARF...
/home/xxx/miniconda3/envs/fmov/lib/python3.9/site-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
SDF get noise poses torch.Size([156, 4, 4])
Using Seg...
Using picture level...
Using emphasize rotation...
Reset based on rotation...
n_images: 156
order_sample: False, detach_ref: False, flow_interval: 10
mode:  train
Traceback (most recent call last):
  File "/home/xxx/fmov_pose/exp_runner.py", line 2073, in <module>
    runner.save_aligned_poses(
  File "/home/xxx/fmov_pose/exp_runner.py", line 1328, in save_aligned_poses
    poses = np.stack(poses)
  File "/home/xxx/fmov/lib/python3.9/site-packages/numpy/core/shape_base.py", line 445, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```
The above error can be reproduced by running `python exp_runner.py --mode train --conf  ./confs/ho3d_virtual.conf --case AP13_ori --global_conf ./confs/ho3d_global_womask.conf`.

How should I fix this?

**Comment by HaixinShi** [comment]
Hello, did it happen at the very begginging? Are you able to find this txt file at "https://github.com/HaixinShi/fmov_pose/blob/master/exp_runner.py#L2067"? If yes, could you show me the content?

**Comment by kgg012392** [comment]
Content of `error_during_progressive_learning.txt`:
```
Exception occurred: indices should be either on cpu or on the same device as the indexed tensor (cpu)
Traceback (most recent call last):
  File "/home/xxx/fmov_pose/exp_runner.py", line 2063, in <module>
    runner.train()
  File "/home/xxx/fmov_pose/exp_runner.py", line 482, in train
    data, depth = self.dataset.gen_random_rays_at(
  File "/home/xxx/fmov_pose/models/dataset.py", line 656, in gen_random_rays_at
    color = self.images[img_idx][(pixels_y, pixels_x)]  # batch_size, 3
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Comment by HaixinShi** [comment]
Hello, it looks like it is related to environment. The code and environment instructions work well in Colab and Docker, maybe you could double check the version of libraries.  Could you debug it a little bit? Like putting all tensors to the same GPU.
```
device = torch.device("cuda:0")
X = X.to(device)
```
If you find solution, feel free to leave comments here.

**Comment by kgg012392** [comment]
After fixing the device issue, the code can run. 

How fast is it expected to run on the `spaceinvader` of ML dataset?

Which files store the final output of object pose & mesh? And is there any code or documentation about how should I visualize the result as the demo shown [here](https://haixinshi.github.io/fmov/)?

**Comment by HaixinShi** [comment]
Thanks for posting the questions.

With standard NVIDIA V100 GPU, for most of the datasets, we can finish within 10 hour. Here is the calculation for reference:
(1) For virtual phase: 0.9 minute for estimating pose of a frame. So the total time for virtual phase is 0.9 * frame# minutes
(2) For pose refinement: it is independent of frame number. 24 minute for 10k iteration, and we typically run 150k iterations

[runner.validate_mesh(resolution=512, use_norml_color=True)](https://github.com/HaixinShi/fmov_pose/blob/master/exp_runner.py#L2098) will save the final mesh.
[runner.save_poses_simple()](https://github.com/HaixinShi/fmov_pose/blob/master/exp_runner.py#L2099C12-L2099C39) will save the final pose.
You could also change the mode from "train" mode to other options in the original script, like:
`python exp_runner.py --mode validate_textured_mesh --conf  ./confs/ml_virtual.conf --case spaceinvader_ori --global_conf ./confs/ml_global_womask.conf`
There is a sub-folder named "ho3d_global_womask" in "exp/{case}/ours" to show results of global refinement.

I am working on the doc and code for the evaluation and visualization parts. Please stay tuned.
